Fix username parsing in PAM's slash_to_at_username
ubuntu/adsys pull request #1081
Opened 2024-08-29 11:38 UTC by denisonbarbosa

This function is supposed to transform a domain.com\user username to the @ format (i.e. user@domain.com). However, it was leaving the parsed username with bad characters in the end (maybe an off behavior from strncpy or something wrong in our string manipulation). This takes a more "direct" approach by selecting the precise substring that we want to append to the parsed name.

UDENG-4314

2024-08-29 12:04 UTC, didrocks requested changes
isn’t the issue that we just didn’t append `\0` after the second `strncpy`? Like you do with `ret[index] = '\0'`, just determining the right index…

2024-08-29 12:12 UTC, denisonbarbosa commented
> isn’t the issue that we just didn’t append `\0` after the second `strncpy`? Like you do with `ret[index] = '\0'`, just determining the right index…

Nope, it wasn't. `strncpy` added more than just what we wanted to the target string, so adding a `\0` wasn't enough. That's why I replaced the function call.

2024-08-29 12:14 UTC, didrocks commented
> Nope, it wasn't. strncpy added more than just what we wanted to the target string, so adding a \0 wasn't enough. That's why I replaced the function call.

Maybe we should thus pair, I’m pretty sure it’s doable this way and will be more intelligible

2024-08-30 11:32 UTC, didrocks approved these changes
way better!

2024-08-30 11:40 UTC, merged