ADMX and ADML generation support for the sharing policy.
ubuntu/adsys pull request #429
Opened 2022-09-29 15:41 UTC by denisonbarbosa

Added the required files to generate the ADM(X&L) templates for the sharing policy for the user.

DEENG-462

2022-09-29 15:42 UTC, denisonbarbosa commented
Might still need some tweaks (and probably some renaming), but we can discuss it along the PR.

2022-09-30 06:55 UTC, didrocks requested changes
This is going to be interesting. We are going to have the same key twice which is handled by adsys without any issue as they are in separate `class`. However, the displayname "Drive Mapping" is not typed (I think you decided to have them with different names?). Not a biggie, we can revisit anyway when implementing the maching policy as we are not going to cut a release without it, so no beakage.

(I think we may end up with either different category name or different key name).

I made some suggestion on the text explanation itself, otherwise, this looks good to me and it’s indeed only what is needed.

You probably noticed the PR created automatically against your branch (https://github.com/ubuntu/adsys/pull/430). It looks OK to me :) What we will to do is:
- get the text explanation ok
- wait for https://github.com/ubuntu/adsys/pull/430 to be updated and if happy, merge it to your branch
- then, we can get this branch merged.

Nice work! :)

2022-09-30 06:55 UTC, didrocks commented on cmd/admxgen/defs/mount.yaml
> +    The mounts listed will be appended to the list of mounts referenced higher in the GPO hierarchy.
Precise that the mounts will be deduplicated. Also that both anynomous mount and those needing kerberos credentials. are handled.

And also, maybe precise the format of the text mount, like protocol:///?
You can add some example like, the anonymous tag and one with a protocol, telling it’s going to try to be authenticated in comments.

2022-09-30 14:13 UTC, didrocks commented on cmd/admxgen/defs/mount.yaml
> +    Anonymous and Kerberos validated mounts will be handled automatically.
Are we sure we will be able to handle Kerberos for the computer?

2022-09-30 14:14 UTC, didrocks reviewed
Let’s maybe only stage the user for now and do the computer afterwards?

2022-09-30 14:14 UTC, didrocks commented
The new text looks good otherwise :)

2022-10-03 07:01 UTC, didrocks approved these changes

2022-10-03 12:19 UTC, merged