Add integration tests for the winbind backend
ubuntu/adsys pull request #570
Opened 2023-01-09 14:46 UTC by GabrielNagy

Refactor integration tests to support selecting different backends and add some basic tests for winbind.

We use the same libwbclient mocking logic as the winbind package tests.

DEENG-492

2023-01-10 11:35 UTC, denisonbarbosa approved these changes
Everything looks great to me. Well done!

2023-01-10 16:36 UTC, didrocks requested changes
Some small minor enhancements that can be added. Nice that things start to click like moving the Build utility to reuse in both case :) Well done!
Sad that we can’t really test kinit though. Did you try to build the package and autopkgtests? Some runs as root and it may impact if kinit is run on mock content?

2023-01-10 16:36 UTC, didrocks commented on cmd/adsysd/integration_tests/adsys_test.go
> +	conf := createConf(t, "", "sssd")
This is set on every tests, and the number of induced changes triggers me that it’s maybe a little bit too much.

I think this is a good use case for optional function parameter? (Maybe doing the same for adsysDir too while we are at it). (Default being sssd ofc)

2023-01-10 16:36 UTC, didrocks commented on cmd/adsysd/integration_tests/adsys_test.go
> +`, dir, dir, dir, backend, dir, dir, dir, dir, dir, dir, dir)), 0600)
dir dir dir dir dir oh backend, dir dir dir dir :p

2023-01-10 16:36 UTC, didrocks commented on cmd/adsysd/integration_tests/adsysctl_policy_test.go
> +					if !strings.HasPrefix(krb5.src, "/") {
You can use filepath.IsAbs() and then, don’t need the comment :p

2023-01-10 16:36 UTC, didrocks commented on cmd/adsysd/integration_tests/adsysctl_policy_test.go
> +	mockWinbindLibPath := testutils.BuildWinbindMock(t, "../../../internal/ad/backends/winbind")
integration tests have a global variable (OMG!) named rootProjectDir :)

2023-01-11 09:53 UTC, didrocks approved these changes
The changes LGTM then! It’s way more readable now with the conf using optionl types.

Thanks for checking on the autopkgtests and package build.

2023-01-11 09:58 UTC, merged