Add documentation for using Winbind as a backend
ubuntu/adsys pull request #576
Opened 2023-01-11 18:31 UTC by GabrielNagy

DEENG-493

2023-01-12 16:21 UTC, didrocks requested changes
Really good update!

* one (+ its repetition) or a real comment
* one precision that we want to specify ubuntu specific instructions
* one question to double check
* one random "thank" comment :)

2023-01-12 16:21 UTC, didrocks commented on conf.example/adsys.yaml
> +# Winbind configuration
Maybe add a comment like "if backend: winbind is selected"?

2023-01-12 16:21 UTC, didrocks commented on doc/02.-Prerequisites.md
> -Authentication of Ubuntu against the Active Directory server requires to configure SSSD and Kerberos. SSSD will then retrieve the credentials and the initial security policy of the `Default Domain Po
attention to details :) Thanks!

2023-01-12 16:21 UTC, didrocks commented on doc/02.-Prerequisites.md
> +In addition, Winbind requires additional dependencies to be installed. They can be installed by executing the following command, prior to ADSys:
add something like, "for instance, on ubuntu…"

2023-01-12 16:21 UTC, didrocks commented on doc/02.-Prerequisites.md
> +If Winbind is used as a backend, the account has to be specified in the following format: `DOMAIN\\USER`.
hum, winbind doesn’t support USER@DOMAIN too? I don’t remember with the amount of testing we did, you are probably right, but just checking :)

2023-01-12 16:21 UTC, didrocks commented on doc/10.-The-adsys-daemon.md
> +# Winbind configuration
check the comment on the config too. (I start to think we should automate this update too)

2023-01-12 16:59 UTC, didrocks commented on doc/02.-Prerequisites.md
> +If Winbind is used as a backend, the account has to be specified in the following format: `DOMAIN\\USER`.
\o/

2023-01-12 17:00 UTC, didrocks approved these changes
Excellent job!

2023-01-13 11:23 UTC, denisonbarbosa approved these changes
LGTM. Well done!

2023-01-13 11:29 UTC, merged