Replacing os.WriteFile after init in the config tests
ubuntu/adsys pull request #614
Opened 2023-02-27 17:57 UTC by denisonbarbosa

Viper relies on fsnotify to trigger a config update. However, the fsnotify docs state that the Write event is also triggered by truncating the file. This means that the update callback was being called too soon and we were unmarshaling the file contents before they were properly written.
To avoid this problem, the os.WriteFile call had to be replaced and now we manually open the file, write to it and then close it to properly flush the changes and only then have the callback triggered.

DEENG-607

2023-02-27 20:47 UTC, CarlosNihelton approved these changes
Straightforward fix. LGTM 👍🏽

2023-02-28 07:43 UTC, didrocks requested changes
As we discussed yesterday, nice work and hunting!
One change requested to ensure the file is always closed.

However, we also mentionned yesterday to open a file in viper for listening to the rename event if this is missed and referenced it here. I think this should be done before merging.

2023-02-28 07:43 UTC, didrocks commented on internal/config/config_test.go
> +				_, err = configFile.WriteString(tc.changeConfigWith)
If write faiols here, the file is not closed, You still need to defer the Close after the first require.NoError in addition to the manual close.

2023-02-28 11:13 UTC, denisonbarbosa commented
> However, we also mentionned yesterday to open a file in viper for listening to the rename event if this is missed and referenced it here. I think this should be done before merging.

@didrocks This is a bit tricky... The `fsnotify.Rename` event is actually two events at once:
```Go
//   fsnotify.Rename    A path was renamed. A rename is always sent with the
//                      old path as Event.Name, and a Create event will be
//                      sent with the new name. Renames are only sent for
//                      paths that are currently watched; e.g. moving an
//                      unmonitored file into a monitored directory will
//                      show up as just a Create. Similarly, renaming a file
//                      to outside a monitored directory will show up as
//                      only a Rename.
```
Technically, viper is watching for the rename event indirectly (since the watch is done in the directory and renaming a file in the directory will count as a `fsnotify.Create` event). So, the problem with the .new strategy is actually in our code (on line 82 of config.go):
```Go
if e.Op != fsnotify.Write {
    return
}
```
We are only considering `Write` events, which means that the `Create` event is discarded and our tests fail (when trying to rename the file).

2023-02-28 11:32 UTC, didrocks commented
Ah, you mentionned yesterday it was viper not listening to Rename, so maybe we can fix our code if we are the one gating on it and go with the .New() strategy?

2023-02-28 12:10 UTC, denisonbarbosa commented
> Ah, you mentionned yesterday it was viper not listening to Rename, so maybe we can fix our code if we are the one gating on it and go with the + ".new" strategy?

Sure, we can. However, shouldn't we keep the "changing the same file" behavior since it's the one that's more likely to happen in a real use case?

2023-02-28 12:32 UTC, didrocks commented
> However, shouldn't we keep the "changing the same file" behavior since it's the one that's more likely to happen in a real use case?

Good point, you’re right. Actually, hem, 2 tests? :)

2023-02-28 15:15 UTC, didrocks approved these changes
Excellent! Just rename the new test case itself to be more descriptive and then, we are good to go! :)

2023-02-28 15:15 UTC, didrocks commented on internal/config/config_test.go
> +		"Configuration changed indirectly": {
Configuration file overwritten?

2023-02-28 16:28 UTC, merged