Fixing some i18n problems
ubuntu/adsys pull request #658
Opened 2023-03-29 14:16 UTC by denisonbarbosa

We had some issues related to the i18n package. This PR aims to solve them.

2023-03-30 12:54 UTC, CarlosNihelton commented on cmd/adwatchd/commands/run.go
> +		Long:  i18n.G("Can run as a service through the service manager or interactively as a standalone application.\n\nThe program will monitor the configured directories for changes and bump the appropr
```suggestion
Long:  i18n.G("Can run as a service through the service manager or interactively as a standalone application.\n\nThe program will monitor the configured directories for changes and bump the appropriate GPT.ini versions anytime a change is detected.\nIf a GPT.ini file does not exist for a directory, a warning will be issued and the file will be created.\nIf the GPT.ini file is incompatible or malformed, the program will report an error.\n"),
```

The `If the GPT.init...` sentence lives in its own line.

2023-03-30 13:56 UTC, CarlosNihelton commented on cmd/adwatchd/commands/run.go
> +		Long:  i18n.G("Can run as a service through the service manager or interactively as a standalone application.\n\nThe program will monitor the configured directories for changes and bump the appropr
Viewing the diff in the "files" tab made me think that there is:
![image](https://user-images.githubusercontent.com/11138291/228859351-8d96b65b-429c-4a7a-ae5c-48d6706776a5.png)

2023-04-03 08:18 UTC, didrocks requested changes
One requested change, and I think we should, before merging this, consider if we can’t search for an alternative on string extractions.

2023-04-03 08:18 UTC, didrocks commented on cmd/adsysd/main.go
> +	i18n.InitI18nDomain(consts.TEXTDOMAIN)
I think the a declaration is for the daemon below. So I would just move that one up. It’s not C89 :)

2023-04-03 10:06 UTC, EduardGomezEscandell commented
> can we consider/research any other approach to extract the sentences in po files and to be compatible with bacquote?

Regarding extracting the strings: It is easy, I did it as a side thing here https://github.com/EduardGomezEscandell/go-gettext-adapter. I used this to generate PR https://github.com/ubuntu/adsys/pull/659.

The issue is maintaining this code (or a cleaner, better, not-done-in-one-afternoon version of it) and wether it is worth the hassle.

The linked repo already scans and finds the strings, it'd be a question of putting them in our potfile instead of sanitizing them.

2023-07-31 14:42 UTC, didrocks commented
And with the new i18n, I think we can drop this one!

2023-07-31 14:42 UTC, closed without merging