Adding lock to sync policy application
ubuntu/adsys pull request #663
Opened 2023-04-03 12:22 UTC by denisonbarbosa

Added a mutex map to the One Manager to sync the applying process of the multiple policy managers. We don't want to run multiple policy managers concurrently for the same object, so if we start applying a policy to the object, the other managers should wait for it to finish before starting their applying process to that object.

Closes #427

2023-04-03 12:24 UTC, denisonbarbosa commented
Sadly, it ended up in quite some code repetition. We could add a `&sync.Mutex` argument to the specific managers and handle the lock in each of them, but is it better?

2023-04-03 15:15 UTC, didrocks requested changes
I think I didn’t make my point clear: the goal is to have all managers running concurrently per objetName, but only one instance of each manager per object name is running at the same time.

Is that more clear?

2023-04-06 07:01 UTC, didrocks requested changes
It’s good to see those changes in!

Please, refrain from doing refactoring not related to the current PR (see my comment about it). Apart from that, one nitpick and one simplification (let’s try to not use pointers when they are not necessary, unless we are using a copy of the main object).

Nice work!

2023-04-06 07:01 UTC, didrocks commented on internal/policies/apparmor/apparmor.go
> +	mu *sync.Mutex // Prevents multiple instances of apparmor from running concurrenctly
I don’t think we need a pointer here, as we only have one manager instance. Let’s keep it simple and avoid using pointers.

2023-04-06 10:44 UTC, denisonbarbosa commented on internal/policies/manager.go
> -	var g errgroup.Group
Can I add a comment to it to prevent us from forgetting about that?

2023-04-06 10:52 UTC, didrocks commented on internal/policies/manager.go
> -	var g errgroup.Group
sure :)

2023-04-06 12:21 UTC, didrocks requested changes
I think you miss a push?

2023-04-06 12:21 UTC, didrocks commented on internal/policies/dconf/dconf.go
> +	// 		- Any number of users can have the policy applied in parallel;
there are still 2? :p

2023-04-06 12:21 UTC, didrocks commented on internal/policies/apparmor/apparmor.go
> +	mu *sync.Mutex // Prevents multiple instances of apparmor from running concurrenctly
the pointer is still around? :)

2023-04-06 12:34 UTC, didrocks approved these changes
Now I see all the changes! That looks so much better :)

2023-04-06 12:57 UTC, merged