tests: add e2e tests for all policy managers
ubuntu/adsys pull request #891
Opened 2024-01-15 10:47 UTC by GabrielNagy

I recommend reviewing this one commit by commit since it includes lots of minor fixes and improvements to support the e2e tests implementation. There's more context in the individual commit messages too.

I've ran the suite on focal, jammy and mantic and got passing runs, however I'll tinker with them some more once everything is set up on GitHub Actions (as part of a follow-up card).

Because this PR includes changes to the VM template provisioning script, we will have to refresh the templates once this is merged.

Fixes UDENG-1360

2024-01-16 09:51 UTC, denisonbarbosa reviewed
I like it a lot, nicely done! Just one comment, but no big deal

2024-01-16 09:51 UTC, denisonbarbosa commented on e2e/internal/remote/remote.go
> +		default:
You only use the context for timing out the loop here. Can't we just do ```<-time.After(time.Minute)``` instead?

2024-01-16 09:51 UTC, denisonbarbosa commented on e2e/cmd/run_tests/03_test_non_pro_managers/main.go
> +	sshKey, err = command.ValidateAndExpandPath(cmd.Inventory.SSHKeyPath, command.DefaultSSHKeyPath)
We could use named return instead and avoid having the `var err error` line, but I'm not 100% sure what's the best approach here.

2024-01-23 09:06 UTC, didrocks requested changes
Excellent work! I don’t have that may things to suggest, only minor things I spot.

I think this is really a very good way for us to ensure that most of our policies and base commands works.

Just curious, do you consider that the non pro and then pro attach + reboot is what is covering the "reupdate policies?"

I think there is also reupdate policies while the machine is booted, is there any plans for this? (I think we discussed that one the spec, but can’t remember). But already, just the fact that we got to that e2e level of tests, I’m thrilled! :)

2024-01-23 09:06 UTC, didrocks commented on e2e/internal/remote/remote.go
> +func (c Client) Close() error {
I would put a pointer on Client here, just to signal we change something on the underlying object (even if it’s a copy of an object handling a pointer has no special effect, but at least, semantically, we signal it correct)

2024-01-23 09:06 UTC, didrocks commented on e2e/scripts/patches/focal.patch
> ++               golang-1.21-go,
I always hate to read diffs of diffs :p

2024-01-23 10:39 UTC, didrocks commented on e2e/cmd/run_tests/04_test_pro_managers/main.go
> +	// Workaround user mounts only being applied on graphical sessions
retraced, Denis corrected me :) 

I think maybe a comment with the new client will be helpful!

2024-01-23 12:03 UTC, didrocks approved these changes
All good from my POV! Excellent work :)

2024-01-23 12:19 UTC, denisonbarbosa approved these changes
Looks good to me. Nicely done!

2024-01-23 13:27 UTC, merged