tests(e2e): collect and upload e2e test logs on failure
ubuntu/adsys pull request #942
Opened 2024-03-08 15:22 UTC by GabrielNagy

In case we get an error during the tests, attempt to collect some potentially relevant logs from the remote client and download them to `logs/$HOSTNAME`. 

We currently collect apport logs, journalctl, and an archive of `/var/log` (excluding `/var/log/journal`). They are uploaded as GH actions artifacts only if tests fail.

Example: https://github.com/GabrielNagy/adsys/actions/runs/8205179603

Fixes UDENG-1537

2024-03-08 16:43 UTC, didrocks requested changes
I have few suggestions and an opened question on this Friday! :)

2024-03-08 16:43 UTC, didrocks commented on e2e/cmd/run_tests/04_test_pro_managers/main.go
> +		client.CollectLogs(ctx, cmd.Inventory.Hostname)
shouldn’t we follow the same pattern of `defer()` to collect the logs so that if we add more tests/teardown, we always try to do this?

2024-03-08 16:43 UTC, didrocks commented on e2e/internal/remote/remote.go
> +	_, err = c.Run(ctx, "journalctl --no-pager --output=short-precise --no-hostname > /root/journal")
I suggest that we rather ensure that our apport hook collect the journal then for us as it means we will likely need it for accurate bug reports.

2024-03-08 16:43 UTC, didrocks commented on e2e/internal/remote/remote.go
> +	if _, err := c.Run(ctx, "tar --exclude=/var/log/journal -czf /root/varlog.tar.gz /var/log"); err != nil {
maybe we should collect that too in the apport hook?

2024-03-11 15:42 UTC, denisonbarbosa approved these changes
Looks good to me (besides what Didier already pointed out)! Nice job!

2024-03-11 15:49 UTC, didrocks approved these changes
With the few things already discussed, +1. Well done!

2024-03-11 16:40 UTC, merged